<?
$hijri = 0; 
$ramadan = 0; 
$co["algeria"] = "الجزائر"; $coen["algeria"] = "Algeria";  $dst["algeria"] = 0; $ram["algeria"] = "0"; $con["algeria"] = "alg"; $method["algeria"] = "eg";
$co["egypt"] = "مصر"; $coen["egypt"] = "Egypt";  $dst["egypt"] = 0; $ram["egypt"] = "0"; $con["egypt"] = "egy"; $method["egypt"] = "eg";
$co["france"] = "فرنسا"; $coen["france"] = "France";  $dst["france"] = 0; $ram["france"] = "0"; $con["france"] = "fra"; $method["france"] = "bo";
$co["iraq"] = "العراق"; $coen["iraq"] = "Iraq";  $dst["iraq"] = 0; $ram["iraq"] = "0"; $con["iraq"] = "ira"; $method["iraq"] = "bo";
$co["italy"] = "ايطاليا"; $coen["italy"] = "Italy";  $dst["italy"] = 0; $ram["italy"] = "0"; $con["italy"] = "ita"; $method["italy"] = "bo";
$co["jordan"] = "الأردن"; $coen["jordan"] = "Jordan";  $dst["jordan"] = 0; $ram["jordan"] = "0"; $con["jordan"] = "jor"; $method["jordan"] = "um";
$co["ksa"] = "السعودية"; $coen["ksa"] = "Saudi Arabia";  $dst["ksa"] = 0; $ram["ksa"] = "0"; $con["ksa"] = "sau"; $method["ksa"] = "um";
$co["kuwait"] = "الكويت"; $coen["kuwait"] = "Kuwait";  $dst["kuwait"] = 0; $ram["kuwait"] = "0"; $con["kuwait"] = "kuw"; $method["kuwait"] = "ka";
$co["lebanon"] = "لبنان"; $coen["lebanon"] = "Lebanon";  $dst["lebanon"] = 0; $ram["lebanon"] = "0"; $con["lebanon"] = "leb"; $method["lebanon"] = "bo";
$co["libya"] = "ليبيا"; $coen["libya"] = "Libya";  $dst["libya"] = 0; $ram["libya"] = "0"; $con["libya"] = "lib"; $method["libya"] = "eg";
$co["morocco"] = "المغرب"; $coen["morocco"] = "Morocco";  $dst["morocco"] = 0; $ram["morocco"] = "0"; $con["morocco"] = "mor"; $method["morocco"] = "bo";
$co["oman"] = "عمان"; $coen["oman"] = "Oman";  $dst["oman"] = 0; $ram["oman"] = "0"; $con["oman"] = "oma"; $method["oman"] = "um";
$co["palestine"] = "فلسطين"; $coen["palestine"] = "Palestine";  $dst["palestine"] = 0; $ram["palestine"] = "0"; $con["palestine"] = "pal"; $method["palestine"] = "bo";
$co["qatar"] = "قطر"; $coen["qatar"] = "Qatar";  $dst["qatar"] = 0; $ram["qatar"] = "0"; $con["qatar"] = "qat"; $method["qatar"] = "um";
$co["sudan"] = "السودان"; $coen["sudan"] = "Sudan";  $dst["sudan"] = 0; $ram["sudan"] = "0"; $con["sudan"] = "sud"; $method["sudan"] = "bo";
$co["syria"] = "سوريا"; $coen["syria"] = "Syria";  $dst["syria"] = 0; $ram["syria"] = "0"; $con["syria"] = "syr"; $method["syria"] = "um";
$co["tunisia"] = "تونس"; $coen["tunisia"] = "Tunisia";  $dst["tunisia"] = 0; $ram["tunisia"] = "0"; $con["tunisia"] = "tun"; $method["tunisia"] = "bo";
$co["uae"] = "الامارات"; $coen["uae"] = "United Arab Emirates";  $dst["uae"] = 0; $ram["uae"] = "0"; $con["uae"] = "uae"; $method["uae"] = "um";
$co["uk"] = "بريطانيا"; $coen["uk"] = "UK";  $dst["uk"] = 0; $ram["uk"] = "0"; $con["uk"] = "uki"; $method["uk"] = "bo";
$co["usa"] = "امريكا"; $coen["usa"] = "USA";  $dst["usa"] = 0; $ram["usa"] = "0"; $con["usa"] = "usa"; $method["usa"] = "us";
$co["yemen"] = "اليمن"; $coen["yemen"] = "Yemen";  $dst["yemen"] = 0; $ram["yemen"] = "0"; $con["yemen"] = "yem"; $method["yemen"] = "um";
$id["abha"] = "2"; $city["abha"] = "abha"; $lats["abha"] = "18.2333000000";  $longs["abha"] = "42.6500000000"; $tzs["abha"] = "3.00"; $car["abha"] = "ابها"; $cen["abha"] = "abha"; $countries["abha"] = "ksa"; $area["abha"] = "um"; $dstz["abha"] = "0"; $ram["abha"] = "0";
$id["abqaiq"] = "1"; $city["abqaiq"] = "abqaiq"; $lats["abqaiq"] = "25.9333300000";  $longs["abqaiq"] = "49.6833300000"; $tzs["abqaiq"] = "3.00"; $car["abqaiq"] = "ابقيق"; $cen["abqaiq"] = "abqaiq"; $countries["abqaiq"] = "ksa"; $area["abqaiq"] = "um"; $dstz["abqaiq"] = "0"; $ram["abqaiq"] = "0";
$id["abudhabi"] = "57"; $city["abudhabi"] = "abudhabi"; $lats["abudhabi"] = "24.4333000000";  $longs["abudhabi"] = "54.6500000000"; $tzs["abudhabi"] = "4.00"; $car["abudhabi"] = "ابو ظبي"; $cen["abudhabi"] = "Abu Dhabi"; $countries["abudhabi"] = "uae"; $area["abudhabi"] = "um"; $dstz["abudhabi"] = "0"; $ram["abudhabi"] = "0";
$id["aden"] = "107"; $city["aden"] = "aden"; $lats["aden"] = "12.7667000000";  $longs["aden"] = "45.0167000000"; $tzs["aden"] = "3.00"; $car["aden"] = "عدن"; $cen["aden"] = "aden"; $countries["aden"] = "yemen"; $area["aden"] = "um"; $dstz["aden"] = "0"; $ram["aden"] = "0";
$id["afif"] = "27"; $city["afif"] = "afif"; $lats["afif"] = "23.9100000000";  $longs["afif"] = "42.9202780000"; $tzs["afif"] = "3.00"; $car["afif"] = "عفيف"; $cen["afif"] = "afif"; $countries["afif"] = "ksa"; $area["afif"] = "um"; $dstz["afif"] = "0"; $ram["afif"] = "0";
$id["agadir"] = "73"; $city["agadir"] = "agadir"; $lats["agadir"] = "30.3833000000";  $longs["agadir"] = "-9.5666700000"; $tzs["agadir"] = "0.00"; $car["agadir"] = "اغادير"; $cen["agadir"] = "agadir"; $countries["agadir"] = "morocco"; $area["agadir"] = "bo"; $dstz["agadir"] = "0"; $ram["agadir"] = "0";
$id["agedabia"] = "96"; $city["agedabia"] = "agedabia"; $lats["agedabia"] = "30.7592000000";  $longs["agedabia"] = "20.2231000000"; $tzs["agedabia"] = "2.00"; $car["agedabia"] = "اجدابيا"; $cen["agedabia"] = "agedabia"; $countries["agedabia"] = "libya"; $area["agedabia"] = "eg"; $dstz["agedabia"] = "0"; $ram["agedabia"] = "0";
$id["ajman"] = "131"; $city["ajman"] = "ajman"; $lats["ajman"] = "25.4061000000";  $longs["ajman"] = "55.4428000000"; $tzs["ajman"] = "4.00"; $car["ajman"] = "عجمان"; $cen["ajman"] = "ajman"; $countries["ajman"] = "uae"; $area["ajman"] = "um"; $dstz["ajman"] = "0"; $ram["ajman"] = "0";
$id["akka"] = "130"; $city["akka"] = "akka"; $lats["akka"] = "32.9236000000";  $longs["akka"] = "35.0728000000"; $tzs["akka"] = "2.00"; $car["akka"] = "عكا"; $cen["akka"] = "akka"; $countries["akka"] = "palestine"; $area["akka"] = "bo"; $dstz["akka"] = "0"; $ram["akka"] = "0";
$id["alain"] = "129"; $city["alain"] = "alain"; $lats["alain"] = "24.2167000000";  $longs["alain"] = "55.7667000000"; $tzs["alain"] = "4.00"; $car["alain"] = "العين"; $cen["alain"] = "alain"; $countries["alain"] = "uae"; $area["alain"] = "um"; $dstz["alain"] = "0"; $ram["alain"] = "0";
$id["albahah"] = "3"; $city["albahah"] = "albahah"; $lats["albahah"] = "20.0000000000";  $longs["albahah"] = "41.5000000000"; $tzs["albahah"] = "3.00"; $car["albahah"] = "الباحة"; $cen["albahah"] = "albahah"; $countries["albahah"] = "ksa"; $area["albahah"] = "um"; $dstz["albahah"] = "0"; $ram["albahah"] = "0";
$id["aleppo"] = "123"; $city["aleppo"] = "aleppo"; $lats["aleppo"] = "36.2028000000";  $longs["aleppo"] = "37.1586000000"; $tzs["aleppo"] = "2.00"; $car["aleppo"] = "حلب"; $cen["aleppo"] = "aleppo"; $countries["aleppo"] = "syria"; $area["aleppo"] = "um"; $dstz["aleppo"] = "0"; $ram["aleppo"] = "0";
$id["alexandria"] = "37"; $city["alexandria"] = "alexandria"; $lats["alexandria"] = "31.2000000000";  $longs["alexandria"] = "29.9000000000"; $tzs["alexandria"] = "2.00"; $car["alexandria"] = "الاسكندرية"; $cen["alexandria"] = "alexandria"; $countries["alexandria"] = "egypt"; $area["alexandria"] = "eg"; $dstz["alexandria"] = "0"; $ram["alexandria"] = "0";
$id["algeria"] = "63"; $city["algeria"] = "algeria"; $lats["algeria"] = "36.7833000000";  $longs["algeria"] = "3.0500000000"; $tzs["algeria"] = "1.00"; $car["algeria"] = "الجزائر"; $cen["algeria"] = "algeria"; $countries["algeria"] = "algeria"; $area["algeria"] = "bo"; $dstz["algeria"] = "0"; $ram["algeria"] = "0";
$id["alhasa"] = "128"; $city["alhasa"] = "alhasa"; $lats["alhasa"] = "25.3333000000";  $longs["alhasa"] = "49.6333000000"; $tzs["alhasa"] = "3.00"; $car["alhasa"] = "الحسا"; $cen["alhasa"] = "alhasa"; $countries["alhasa"] = "ksa"; $area["alhasa"] = "um"; $dstz["alhasa"] = "0"; $ram["alhasa"] = "0";
$id["amman"] = "103"; $city["amman"] = "amman"; $lats["amman"] = "31.9500000000";  $longs["amman"] = "35.9333000000"; $tzs["amman"] = "2.00"; $car["amman"] = "عمان"; $cen["amman"] = "amman"; $countries["amman"] = "jordan"; $area["amman"] = "um"; $dstz["amman"] = "0"; $ram["amman"] = "0";
$id["annaba"] = "64"; $city["annaba"] = "annaba"; $lats["annaba"] = "36.8333000000";  $longs["annaba"] = "7.8166700000"; $tzs["annaba"] = "1.00"; $car["annaba"] = "عنابة"; $cen["annaba"] = "annaba"; $countries["annaba"] = "algeria"; $area["annaba"] = "bo"; $dstz["annaba"] = "0"; $ram["annaba"] = "0";
$id["arar"] = "26"; $city["arar"] = "arar"; $lats["arar"] = "30.9000000000";  $longs["arar"] = "41.1333000000"; $tzs["arar"] = "3.00"; $car["arar"] = "عرعر"; $cen["arar"] = "arar"; $countries["arar"] = "ksa"; $area["arar"] = "um"; $dstz["arar"] = "0"; $ram["arar"] = "0";
$id["arbil"] = "86"; $city["arbil"] = "arbil"; $lats["arbil"] = "36.1667000000";  $longs["arbil"] = "44.0167000000"; $tzs["arbil"] = "3.00"; $car["arbil"] = "اربيل"; $cen["arbil"] = "arbil"; $countries["arbil"] = "iraq"; $area["arbil"] = "bo"; $dstz["arbil"] = "0"; $ram["arbil"] = "0";
$id["ariana"] = "124"; $city["ariana"] = "ariana"; $lats["ariana"] = "36.8625000000";  $longs["ariana"] = "10.1956000000"; $tzs["ariana"] = "1.00"; $car["ariana"] = "اريانة"; $cen["ariana"] = "ariana"; $countries["ariana"] = "tunisia"; $area["ariana"] = "bo"; $dstz["ariana"] = "0"; $ram["ariana"] = "0";
$id["assiut"] = "40"; $city["assiut"] = "assiut"; $lats["assiut"] = "27.1833000000";  $longs["assiut"] = "31.1833000000"; $tzs["assiut"] = "2.00"; $car["assiut"] = "اسيوط"; $cen["assiut"] = "assiut"; $countries["assiut"] = "egypt"; $area["assiut"] = "eg"; $dstz["assiut"] = "0"; $ram["assiut"] = "0";
$id["aswan"] = "39"; $city["aswan"] = "aswan"; $lats["aswan"] = "24.0833000000";  $longs["aswan"] = "32.8833000000"; $tzs["aswan"] = "2.00"; $car["aswan"] = "اسوان"; $cen["aswan"] = "aswan"; $countries["aswan"] = "egypt"; $area["aswan"] = "eg"; $dstz["aswan"] = "0"; $ram["aswan"] = "0";
$id["atbara"] = "84"; $city["atbara"] = "atbara"; $lats["atbara"] = "17.7000000000";  $longs["atbara"] = "33.9667000000"; $tzs["atbara"] = "3.00"; $car["atbara"] = "عطبره"; $cen["atbara"] = "atbara"; $countries["atbara"] = "sudan"; $area["atbara"] = "bo"; $dstz["atbara"] = "0"; $ram["atbara"] = "0";
$id["baalbek"] = "125"; $city["baalbek"] = "baalbek"; $lats["baalbek"] = "34.0000000000";  $longs["baalbek"] = "36.2000000000"; $tzs["baalbek"] = "2.00"; $car["baalbek"] = "بعلبك"; $cen["baalbek"] = "baalbek"; $countries["baalbek"] = "lebanon"; $area["baalbek"] = "bo"; $dstz["baalbek"] = "1"; $ram["baalbek"] = "0";
$id["baghdad"] = "88"; $city["baghdad"] = "baghdad"; $lats["baghdad"] = "33.2333000000";  $longs["baghdad"] = "44.2333000000"; $tzs["baghdad"] = "3.00"; $car["baghdad"] = "بغداد"; $cen["baghdad"] = "baghdad"; $countries["baghdad"] = "iraq"; $area["baghdad"] = "bo"; $dstz["baghdad"] = "0"; $ram["baghdad"] = "0";
$id["banha"] = "126"; $city["banha"] = "banha"; $lats["banha"] = "30.4333000000";  $longs["banha"] = "31.1667000000"; $tzs["banha"] = "2.00"; $car["banha"] = "بنها"; $cen["banha"] = "banha"; $countries["banha"] = "egypt"; $area["banha"] = "eg"; $dstz["banha"] = "0"; $ram["banha"] = "0";
$id["basrah"] = "87"; $city["basrah"] = "basrah"; $lats["basrah"] = "30.4167000000";  $longs["basrah"] = "47.6500000000"; $tzs["basrah"] = "3.00"; $car["basrah"] = "البصرة"; $cen["basrah"] = "basrah"; $countries["basrah"] = "iraq"; $area["basrah"] = "bo"; $dstz["basrah"] = "0"; $ram["basrah"] = "0";
$id["bechar"] = "132"; $city["bechar"] = "bechar"; $lats["bechar"] = "31.6167000000";  $longs["bechar"] = "-2.2167000000"; $tzs["bechar"] = "1.00"; $car["bechar"] = "بشار"; $cen["bechar"] = "bechar"; $countries["bechar"] = "algeria"; $area["bechar"] = "eg"; $dstz["bechar"] = "0"; $ram["bechar"] = "0";
$id["beersheba"] = "69"; $city["beersheba"] = "beersheba"; $lats["beersheba"] = "31.2333000000";  $longs["beersheba"] = "34.7833000000"; $tzs["beersheba"] = "2.00"; $car["beersheba"] = "بير سبع"; $cen["beersheba"] = "beersheba"; $countries["beersheba"] = "palestine"; $area["beersheba"] = "bo"; $dstz["beersheba"] = "0"; $ram["beersheba"] = "0";
$id["beirut"] = "127"; $city["beirut"] = "beirut"; $lats["beirut"] = "33.8719000000";  $longs["beirut"] = "35.5097000000"; $tzs["beirut"] = "2.00"; $car["beirut"] = "بيروت"; $cen["beirut"] = "beirut"; $countries["beirut"] = "lebanon"; $area["beirut"] = "bo"; $dstz["beirut"] = "1"; $ram["beirut"] = "0";
$id["belfast"] = "133"; $city["belfast"] = "belfast"; $lats["belfast"] = "54.5833000000";  $longs["belfast"] = "-5.9500000000"; $tzs["belfast"] = "0.00"; $car["belfast"] = "بلفاست"; $cen["belfast"] = "belfast"; $countries["belfast"] = "uk"; $area["belfast"] = "bo"; $dstz["belfast"] = "0"; $ram["belfast"] = "0";
$id["benghazi"] = "97"; $city["benghazi"] = "benghazi"; $lats["benghazi"] = "32.1167000000";  $longs["benghazi"] = "20.0667000000"; $tzs["benghazi"] = "2.00"; $car["benghazi"] = "بنغازي"; $cen["benghazi"] = "benghazi"; $countries["benghazi"] = "libya"; $area["benghazi"] = "eg"; $dstz["benghazi"] = "0"; $ram["benghazi"] = "0";
$id["benisuef"] = "41"; $city["benisuef"] = "benisuef"; $lats["benisuef"] = "29.0833000000";  $longs["benisuef"] = "31.0833000000"; $tzs["benisuef"] = "2.00"; $car["benisuef"] = "بني سويف"; $cen["benisuef"] = "Beni Suef"; $countries["benisuef"] = "egypt"; $area["benisuef"] = "eg"; $dstz["benisuef"] = "0"; $ram["benisuef"] = "0";
$id["bisha"] = "5"; $city["bisha"] = "bisha"; $lats["bisha"] = "19.9833000000";  $longs["bisha"] = "42.6167000000"; $tzs["bisha"] = "3.00"; $car["bisha"] = "بيشة"; $cen["bisha"] = "bisha"; $countries["bisha"] = "ksa"; $area["bisha"] = "um"; $dstz["bisha"] = "0"; $ram["bisha"] = "0";
$id["bizerta"] = "134"; $city["bizerta"] = "bizerta"; $lats["bizerta"] = "37.2744000000";  $longs["bizerta"] = "9.8739000000"; $tzs["bizerta"] = "1.00"; $car["bizerta"] = "بيزرت"; $cen["bizerta"] = "bizerta"; $countries["bizerta"] = "tunisia"; $area["bizerta"] = "bo"; $dstz["bizerta"] = "0"; $ram["bizerta"] = "0";
$id["blida"] = "61"; $city["blida"] = "blida"; $lats["blida"] = "36.4686000000";  $longs["blida"] = "2.8289000000"; $tzs["blida"] = "1.00"; $car["blida"] = "بليدا"; $cen["blida"] = "blida"; $countries["blida"] = "algeria"; $area["blida"] = "bo"; $dstz["blida"] = "0"; $ram["blida"] = "0";
$id["boston"] = "122"; $city["boston"] = "boston"; $lats["boston"] = "42.3586000000";  $longs["boston"] = "-71.0605000000"; $tzs["boston"] = "-5.00"; $car["boston"] = "بوسطن"; $cen["boston"] = "Boston"; $countries["boston"] = "usa"; $area["boston"] = "us"; $dstz["boston"] = "1"; $ram["boston"] = "0";
$id["bristol"] = "136"; $city["bristol"] = "bristol"; $lats["bristol"] = "51.4500000000";  $longs["bristol"] = "-2.5833000000"; $tzs["bristol"] = "0.00"; $car["bristol"] = "بريستول"; $cen["bristol"] = "bristol"; $countries["bristol"] = "uk"; $area["bristol"] = "bo"; $dstz["bristol"] = "0"; $ram["bristol"] = "0";
$id["buraidah"] = "4"; $city["buraidah"] = "buraidah"; $lats["buraidah"] = "26.3333000000";  $longs["buraidah"] = "43.9833000000"; $tzs["buraidah"] = "3.00"; $car["buraidah"] = "بريدة"; $cen["buraidah"] = "buraidah"; $countries["buraidah"] = "ksa"; $area["buraidah"] = "um"; $dstz["buraidah"] = "0"; $ram["buraidah"] = "0";
$id["cairo"] = "52"; $city["cairo"] = "cairo"; $lats["cairo"] = "30.0500000000";  $longs["cairo"] = "31.2500000000"; $tzs["cairo"] = "2.00"; $car["cairo"] = "القاهرة"; $cen["cairo"] = "cairo"; $countries["cairo"] = "egypt"; $area["cairo"] = "eg"; $dstz["cairo"] = "0"; $ram["cairo"] = "0";
$id["casablanca"] = "78"; $city["casablanca"] = "casablanca"; $lats["casablanca"] = "33.5667000000";  $longs["casablanca"] = "-7.6667000000"; $tzs["casablanca"] = "0.00"; $car["casablanca"] = "الدار البيضاء"; $cen["casablanca"] = "casablanca"; $countries["casablanca"] = "morocco"; $area["casablanca"] = "bo"; $dstz["casablanca"] = "0"; $ram["casablanca"] = "0";
$id["chicago"] = "118"; $city["chicago"] = "chicago"; $lats["chicago"] = "41.8858000000";  $longs["chicago"] = "-87.6229000000"; $tzs["chicago"] = "-6.00"; $car["chicago"] = "شيكاغو"; $cen["chicago"] = "Chicago"; $countries["chicago"] = "usa"; $area["chicago"] = "us"; $dstz["chicago"] = "1"; $ram["chicago"] = "0";
$id["costantine"] = "65"; $city["costantine"] = "costantine"; $lats["costantine"] = "36.2833000000";  $longs["costantine"] = "6.6766700000"; $tzs["costantine"] = "1.00"; $car["costantine"] = "قسطنطينة"; $cen["costantine"] = "costantine"; $countries["costantine"] = "algeria"; $area["costantine"] = "bo"; $dstz["costantine"] = "0"; $ram["costantine"] = "0";
$id["dallas"] = "119"; $city["dallas"] = "dallas"; $lats["dallas"] = "32.7874000000";  $longs["dallas"] = "-96.7989000000"; $tzs["dallas"] = "-6.00"; $car["dallas"] = "دالاس"; $cen["dallas"] = "Dallas"; $countries["dallas"] = "usa"; $area["dallas"] = "us"; $dstz["dallas"] = "1"; $ram["dallas"] = "0";
$id["damanhour"] = "146"; $city["damanhour"] = "damanhour"; $lats["damanhour"] = "31.0333000000";  $longs["damanhour"] = "30.4667000000"; $tzs["damanhour"] = "2.00"; $car["damanhour"] = "دمنهور"; $cen["damanhour"] = "damanhour"; $countries["damanhour"] = "egypt"; $area["damanhour"] = "eg"; $dstz["damanhour"] = "0"; $ram["damanhour"] = "0";
$id["damascus"] = "143"; $city["damascus"] = "damascus"; $lats["damascus"] = "33.5000000000";  $longs["damascus"] = "36.3000000000"; $tzs["damascus"] = "2.00"; $car["damascus"] = "دمشق"; $cen["damascus"] = "damascus"; $countries["damascus"] = "syria"; $area["damascus"] = "um"; $dstz["damascus"] = "0"; $ram["damascus"] = "0";
$id["damietta"] = "44"; $city["damietta"] = "damietta"; $lats["damietta"] = "31.4166670000";  $longs["damietta"] = "31.8166670000"; $tzs["damietta"] = "2.00"; $car["damietta"] = "دمياط"; $cen["damietta"] = "damietta"; $countries["damietta"] = "egypt"; $area["damietta"] = "eg"; $dstz["damietta"] = "0"; $ram["damietta"] = "0";
$id["dammam"] = "18"; $city["dammam"] = "dammam"; $lats["dammam"] = "26.4333000000";  $longs["dammam"] = "50.1167000000"; $tzs["dammam"] = "3.00"; $car["dammam"] = "الدمام"; $cen["dammam"] = "dammam"; $countries["dammam"] = "ksa"; $area["dammam"] = "um"; $dstz["dammam"] = "0"; $ram["dammam"] = "0";
$id["dawadmi"] = "19"; $city["dawadmi"] = "dawadmi"; $lats["dawadmi"] = "24.5023000000";  $longs["dawadmi"] = "44.3864000000"; $tzs["dawadmi"] = "3.00"; $car["dawadmi"] = "الدوادمي"; $cen["dawadmi"] = "dawadmi"; $countries["dawadmi"] = "ksa"; $area["dawadmi"] = "um"; $dstz["dawadmi"] = "0"; $ram["dawadmi"] = "0";
$id["dhahran"] = "25"; $city["dhahran"] = "dhahran"; $lats["dhahran"] = "26.3000000000";  $longs["dhahran"] = "50.1333000000"; $tzs["dhahran"] = "3.00"; $car["dhahran"] = "الظهران"; $cen["dhahran"] = "dhahran"; $countries["dhahran"] = "ksa"; $area["dhahran"] = "um"; $dstz["dhahran"] = "0"; $ram["dhahran"] = "0";
$id["dhamar"] = "108"; $city["dhamar"] = "dhamar"; $lats["dhamar"] = "14.5500000000";  $longs["dhamar"] = "44.4017000000"; $tzs["dhamar"] = "3.00"; $car["dhamar"] = "ذمار"; $cen["dhamar"] = "dhamar"; $countries["dhamar"] = "yemen"; $area["dhamar"] = "um"; $dstz["dhamar"] = "0"; $ram["dhamar"] = "0";
$id["diriyah"] = "17"; $city["diriyah"] = "diriyah"; $lats["diriyah"] = "24.7333330000";  $longs["diriyah"] = "46.5666670000"; $tzs["diriyah"] = "3.00"; $car["diriyah"] = "الدرعية"; $cen["diriyah"] = "diriyah"; $countries["diriyah"] = "ksa"; $area["diriyah"] = "um"; $dstz["diriyah"] = "0"; $ram["diriyah"] = "0";
$id["doha"] = "135"; $city["doha"] = "doha"; $lats["doha"] = "25.2867000000";  $longs["doha"] = "51.5333000000"; $tzs["doha"] = "3.00"; $car["doha"] = "الدوحة"; $cen["doha"] = "doha"; $countries["doha"] = "qatar"; $area["doha"] = "um"; $dstz["doha"] = "0"; $ram["doha"] = "0";
$id["duba"] = "23"; $city["duba"] = "duba"; $lats["duba"] = "27.3516000000";  $longs["duba"] = "35.6908000000"; $tzs["duba"] = "3.00"; $car["duba"] = "ضبا"; $cen["duba"] = "duba"; $countries["duba"] = "ksa"; $area["duba"] = "um"; $dstz["duba"] = "0"; $ram["duba"] = "0";
$id["dubai"] = "58"; $city["dubai"] = "dubai"; $lats["dubai"] = "24.9500000000";  $longs["dubai"] = "55.3333330000"; $tzs["dubai"] = "4.00"; $car["dubai"] = "دبي"; $cen["dubai"] = "dubai"; $countries["dubai"] = "uae"; $area["dubai"] = "um"; $dstz["dubai"] = "0"; $ram["dubai"] = "0";
$id["einelsokhna"] = "147"; $city["einelsokhna"] = "einelsokhna"; $lats["einelsokhna"] = "29.5833000000";  $longs["einelsokhna"] = "32.3500000000"; $tzs["einelsokhna"] = "2.00"; $car["einelsokhna"] = "عين السخنة"; $cen["einelsokhna"] = "einelsokhna"; $countries["einelsokhna"] = "egypt"; $area["einelsokhna"] = "eg"; $dstz["einelsokhna"] = "0"; $ram["einelsokhna"] = "0";
$id["elarish"] = "148"; $city["elarish"] = "elarish"; $lats["elarish"] = "31.1244000000";  $longs["elarish"] = "33.8006000000"; $tzs["elarish"] = "2.00"; $car["elarish"] = "العريش"; $cen["elarish"] = "elarish"; $countries["elarish"] = "egypt"; $area["elarish"] = "eg"; $dstz["elarish"] = "0"; $ram["elarish"] = "0";
$id["elat"] = "68"; $city["elat"] = "elat"; $lats["elat"] = "29.5500000000";  $longs["elat"] = "34.9500000000"; $tzs["elat"] = "2.00"; $car["elat"] = "ايلات"; $cen["elat"] = "elat"; $countries["elat"] = "palestine"; $area["elat"] = "bo"; $dstz["elat"] = "0"; $ram["elat"] = "0";
$id["fallujah"] = "89"; $city["fallujah"] = "fallujah"; $lats["fallujah"] = "33.3333000000";  $longs["fallujah"] = "43.7667000000"; $tzs["fallujah"] = "3.00"; $car["fallujah"] = "الفلوجة"; $cen["fallujah"] = "fallujah"; $countries["fallujah"] = "iraq"; $area["fallujah"] = "bo"; $dstz["fallujah"] = "0"; $ram["fallujah"] = "0";
$id["fayoom"] = "51"; $city["fayoom"] = "fayoom"; $lats["fayoom"] = "29.3167000000";  $longs["fayoom"] = "30.8333000000"; $tzs["fayoom"] = "2.00"; $car["fayoom"] = "الفيوم"; $cen["fayoom"] = "fayoom"; $countries["fayoom"] = "egypt"; $area["fayoom"] = "eg"; $dstz["fayoom"] = "0"; $ram["fayoom"] = "0";
$id["fez"] = "76"; $city["fez"] = "fez"; $lats["fez"] = "34.0833000000";  $longs["fez"] = "-4.9500000000"; $tzs["fez"] = "0.00"; $car["fez"] = "فاس"; $cen["fez"] = "fez"; $countries["fez"] = "morocco"; $area["fez"] = "bo"; $dstz["fez"] = "0"; $ram["fez"] = "0";
$id["fujayrah"] = "149"; $city["fujayrah"] = "fujayrah"; $lats["fujayrah"] = "25.1333000000";  $longs["fujayrah"] = "56.2500000000"; $tzs["fujayrah"] = "4.00"; $car["fujayrah"] = "الفجيرة"; $cen["fujayrah"] = "fujayrah"; $countries["fujayrah"] = "uae"; $area["fujayrah"] = "um"; $dstz["fujayrah"] = "0"; $ram["fujayrah"] = "0";
$id["gabes"] = "150"; $city["gabes"] = "gabes"; $lats["gabes"] = "33.8833000000";  $longs["gabes"] = "10.1167000000"; $tzs["gabes"] = "1.00"; $car["gabes"] = "قابس"; $cen["gabes"] = "gabes"; $countries["gabes"] = "tunisia"; $area["gabes"] = "bo"; $dstz["gabes"] = "0"; $ram["gabes"] = "0";
$id["gaza"] = "71"; $city["gaza"] = "gaza"; $lats["gaza"] = "31.5333000000";  $longs["gaza"] = "34.4333000000"; $tzs["gaza"] = "2.00"; $car["gaza"] = "غزة"; $cen["gaza"] = "gaza"; $countries["gaza"] = "palestine"; $area["gaza"] = "bo"; $dstz["gaza"] = "0"; $ram["gaza"] = "0";
$id["giza"] = "43"; $city["giza"] = "giza"; $lats["giza"] = "30.0167000000";  $longs["giza"] = "31.2167000000"; $tzs["giza"] = "2.00"; $car["giza"] = "الجيزة"; $cen["giza"] = "giza"; $countries["giza"] = "egypt"; $area["giza"] = "eg"; $dstz["giza"] = "0"; $ram["giza"] = "0";
$id["glasgow"] = "151"; $city["glasgow"] = "glasgow"; $lats["glasgow"] = "55.8333000000";  $longs["glasgow"] = "-4.2500000000"; $tzs["glasgow"] = "0.00"; $car["glasgow"] = "جلاسجو"; $cen["glasgow"] = "glasgow"; $countries["glasgow"] = "uk"; $area["glasgow"] = "bo"; $dstz["glasgow"] = "0"; $ram["glasgow"] = "0";
$id["hafr"] = "12"; $city["hafr"] = "hafr"; $lats["hafr"] = "28.4341670000";  $longs["hafr"] = "45.9636110000"; $tzs["hafr"] = "3.00"; $car["hafr"] = "حفر الباطن"; $cen["hafr"] = "Hafr Al Batin"; $countries["hafr"] = "ksa"; $area["hafr"] = "um"; $dstz["hafr"] = "0"; $ram["hafr"] = "0";
$id["haifa"] = "70"; $city["haifa"] = "haifa"; $lats["haifa"] = "32.8156000000";  $longs["haifa"] = "34.9892000000"; $tzs["haifa"] = "2.00"; $car["haifa"] = "حيفا"; $cen["haifa"] = "haifa"; $countries["haifa"] = "palestine"; $area["haifa"] = "bo"; $dstz["haifa"] = "0"; $ram["haifa"] = "0";
$id["hail"] = "11"; $city["hail"] = "hail"; $lats["hail"] = "27.4333000000";  $longs["hail"] = "41.6833000000"; $tzs["hail"] = "3.00"; $car["hail"] = "حائل"; $cen["hail"] = "hail"; $countries["hail"] = "ksa"; $area["hail"] = "um"; $dstz["hail"] = "0"; $ram["hail"] = "0";
$id["hama"] = "156"; $city["hama"] = "hama"; $lats["hama"] = "35.1667000000";  $longs["hama"] = "36.6667000000"; $tzs["hama"] = "2.00"; $car["hama"] = "حماه"; $cen["hama"] = "hama"; $countries["hama"] = "syria"; $area["hama"] = "um"; $dstz["hama"] = "0"; $ram["hama"] = "0";
$id["hasakeh"] = "157"; $city["hasakeh"] = "hasakeh"; $lats["hasakeh"] = "36.4833000000";  $longs["hasakeh"] = "40.7500000000"; $tzs["hasakeh"] = "2.00"; $car["hasakeh"] = "الحسكة"; $cen["hasakeh"] = "hasakeh"; $countries["hasakeh"] = "syria"; $area["hasakeh"] = "um"; $dstz["hasakeh"] = "0"; $ram["hasakeh"] = "0";
$id["hawalli"] = "94"; $city["hawalli"] = "hawalli"; $lats["hawalli"] = "29.3167000000";  $longs["hawalli"] = "48.0333000000"; $tzs["hawalli"] = "3.00"; $car["hawalli"] = "حولي"; $cen["hawalli"] = "hawalli"; $countries["hawalli"] = "kuwait"; $area["hawalli"] = "ka"; $dstz["hawalli"] = "0"; $ram["hawalli"] = "0";
$id["hodeida"] = "109"; $city["hodeida"] = "hodeida"; $lats["hodeida"] = "14.8000000000";  $longs["hodeida"] = "43.2000000000"; $tzs["hodeida"] = "3.00"; $car["hodeida"] = "الحديدة"; $cen["hodeida"] = "hodeida"; $countries["hodeida"] = "yemen"; $area["hodeida"] = "um"; $dstz["hodeida"] = "0"; $ram["hodeida"] = "0";
$id["hofuf"] = "35"; $city["hofuf"] = "hofuf"; $lats["hofuf"] = "25.3833330000";  $longs["hofuf"] = "49.5833330000"; $tzs["hofuf"] = "3.00"; $car["hofuf"] = "الهفوف"; $cen["hofuf"] = "hofuf"; $countries["hofuf"] = "ksa"; $area["hofuf"] = "um"; $dstz["hofuf"] = "0"; $ram["hofuf"] = "0";
$id["homs"] = "158"; $city["homs"] = "homs"; $lats["homs"] = "34.2500000000";  $longs["homs"] = "38.0000000000"; $tzs["homs"] = "2.00"; $car["homs"] = "حمص"; $cen["homs"] = "homs"; $countries["homs"] = "syria"; $area["homs"] = "um"; $dstz["homs"] = "0"; $ram["homs"] = "0";
$id["hurgada"] = "50"; $city["hurgada"] = "hurgada"; $lats["hurgada"] = "27.1500000000";  $longs["hurgada"] = "33.7167000000"; $tzs["hurgada"] = "2.00"; $car["hurgada"] = "الغردقة"; $cen["hurgada"] = "hurgada"; $countries["hurgada"] = "egypt"; $area["hurgada"] = "eg"; $dstz["hurgada"] = "0"; $ram["hurgada"] = "0";
$id["ibb"] = "110"; $city["ibb"] = "ibb"; $lats["ibb"] = "13.9667000000";  $longs["ibb"] = "44.1833000000"; $tzs["ibb"] = "3.00"; $car["ibb"] = "اب"; $cen["ibb"] = "ibb"; $countries["ibb"] = "yemen"; $area["ibb"] = "um"; $dstz["ibb"] = "0"; $ram["ibb"] = "0";
$id["irbid"] = "102"; $city["irbid"] = "irbid"; $lats["irbid"] = "32.5556000000";  $longs["irbid"] = "35.8500000000"; $tzs["irbid"] = "2.00"; $car["irbid"] = "اربد"; $cen["irbid"] = "irbid"; $countries["irbid"] = "jordan"; $area["irbid"] = "um"; $dstz["irbid"] = "0"; $ram["irbid"] = "0";
$id["ismailia"] = "38"; $city["ismailia"] = "ismailia"; $lats["ismailia"] = "30.5833330000";  $longs["ismailia"] = "32.2667000000"; $tzs["ismailia"] = "2.00"; $car["ismailia"] = "الاسماعيلي"; $cen["ismailia"] = "ismailia"; $countries["ismailia"] = "egypt"; $area["ismailia"] = "eg"; $dstz["ismailia"] = "0"; $ram["ismailia"] = "0";
$id["jahra"] = "93"; $city["jahra"] = "jahra"; $lats["jahra"] = "29.3333000000";  $longs["jahra"] = "47.6667000000"; $tzs["jahra"] = "3.00"; $car["jahra"] = "الجهراء"; $cen["jahra"] = "jahra"; $countries["jahra"] = "kuwait"; $area["jahra"] = "ka"; $dstz["jahra"] = "0"; $ram["jahra"] = "0";
$id["jawf"] = "9"; $city["jawf"] = "jawf"; $lats["jawf"] = "29.7833000000";  $longs["jawf"] = "39.8333000000"; $tzs["jawf"] = "3.00"; $car["jawf"] = "الجوف"; $cen["jawf"] = "jawf"; $countries["jawf"] = "ksa"; $area["jawf"] = "um"; $dstz["jawf"] = "0"; $ram["jawf"] = "0";
$id["jeddah"] = "8"; $city["jeddah"] = "jeddah"; $lats["jeddah"] = "21.7000000000";  $longs["jeddah"] = "39.1833000000"; $tzs["jeddah"] = "3.00"; $car["jeddah"] = "جده"; $cen["jeddah"] = "jeddah"; $countries["jeddah"] = "ksa"; $area["jeddah"] = "um"; $dstz["jeddah"] = "0"; $ram["jeddah"] = "0";
$id["jerusalem"] = "67"; $city["jerusalem"] = "jerusalem"; $lats["jerusalem"] = "31.8667000000";  $longs["jerusalem"] = "35.2167000000"; $tzs["jerusalem"] = "2.00"; $car["jerusalem"] = "القدس"; $cen["jerusalem"] = "jerusalem"; $countries["jerusalem"] = "palestine"; $area["jerusalem"] = "bo"; $dstz["jerusalem"] = "0"; $ram["jerusalem"] = "0";
$id["jizan"] = "10"; $city["jizan"] = "jizan"; $lats["jizan"] = "16.9000000000";  $longs["jizan"] = "42.5833000000"; $tzs["jizan"] = "3.00"; $car["jizan"] = "جيزان"; $cen["jizan"] = "jizan"; $countries["jizan"] = "ksa"; $area["jizan"] = "um"; $dstz["jizan"] = "0"; $ram["jizan"] = "0";
$id["jubail"] = "7"; $city["jubail"] = "jubail"; $lats["jubail"] = "27.0500000000";  $longs["jubail"] = "49.4000000000"; $tzs["jubail"] = "3.00"; $car["jubail"] = "الجبيل"; $cen["jubail"] = "jubail"; $countries["jubail"] = "ksa"; $area["jubail"] = "um"; $dstz["jubail"] = "0"; $ram["jubail"] = "0";
$id["kafrelsheikh"] = "53"; $city["kafrelsheikh"] = "kafrelsheikh"; $lats["kafrelsheikh"] = "31.1100000000";  $longs["kafrelsheikh"] = "30.9400000000"; $tzs["kafrelsheikh"] = "2.00"; $car["kafrelsheikh"] = "كفر الشيخ"; $cen["kafrelsheikh"] = "Kafr El Sheikh"; $countries["kafrelsheikh"] = "egypt"; $area["kafrelsheikh"] = "eg"; $dstz["kafrelsheikh"] = "0"; $ram["kafrelsheikh"] = "0";
$id["karbala"] = "90"; $city["karbala"] = "karbala"; $lats["karbala"] = "32.6000000000";  $longs["karbala"] = "44.0333000000"; $tzs["karbala"] = "3.00"; $car["karbala"] = "كربلاء"; $cen["karbala"] = "karbala"; $countries["karbala"] = "iraq"; $area["karbala"] = "bo"; $dstz["karbala"] = "0"; $ram["karbala"] = "0";
$id["kenitra"] = "77"; $city["kenitra"] = "kenitra"; $lats["kenitra"] = "34.3000000000";  $longs["kenitra"] = "-6.6000000000"; $tzs["kenitra"] = "0.00"; $car["kenitra"] = "القنيطرة"; $cen["kenitra"] = "kenitra"; $countries["kenitra"] = "morocco"; $area["kenitra"] = "bo"; $dstz["kenitra"] = "0"; $ram["kenitra"] = "0";
$id["khafji"] = "15"; $city["khafji"] = "khafji"; $lats["khafji"] = "28.4337000000";  $longs["khafji"] = "48.4988000000"; $tzs["khafji"] = "3.00"; $car["khafji"] = "الخفجي"; $cen["khafji"] = "khafji"; $countries["khafji"] = "ksa"; $area["khafji"] = "um"; $dstz["khafji"] = "0"; $ram["khafji"] = "0";
$id["khamis"] = "16"; $city["khamis"] = "khamis"; $lats["khamis"] = "18.3000000000";  $longs["khamis"] = "42.8000000000"; $tzs["khamis"] = "3.00"; $car["khamis"] = "خميس مشيط"; $cen["khamis"] = "Khamis Mushait"; $countries["khamis"] = "ksa"; $area["khamis"] = "um"; $dstz["khamis"] = "0"; $ram["khamis"] = "0";
$id["kharj"] = "14"; $city["kharj"] = "kharj"; $lats["kharj"] = "24.1667000000";  $longs["kharj"] = "47.5000000000"; $tzs["kharj"] = "3.00"; $car["kharj"] = "الخرج"; $cen["kharj"] = "kharj"; $countries["kharj"] = "ksa"; $area["kharj"] = "um"; $dstz["kharj"] = "0"; $ram["kharj"] = "0";
$id["khartoum"] = "82"; $city["khartoum"] = "khartoum"; $lats["khartoum"] = "15.6000000000";  $longs["khartoum"] = "32.5500000000"; $tzs["khartoum"] = "3.00"; $car["khartoum"] = "الخرطوم"; $cen["khartoum"] = "khartoum"; $countries["khartoum"] = "sudan"; $area["khartoum"] = "bo"; $dstz["khartoum"] = "0"; $ram["khartoum"] = "0";
$id["khobar"] = "13"; $city["khobar"] = "khobar"; $lats["khobar"] = "26.2931000000";  $longs["khobar"] = "50.2033000000"; $tzs["khobar"] = "3.00"; $car["khobar"] = "الخبر"; $cen["khobar"] = "khobar"; $countries["khobar"] = "ksa"; $area["khobar"] = "um"; $dstz["khobar"] = "0"; $ram["khobar"] = "0";
$id["kuwait"] = "95"; $city["kuwait"] = "kuwait"; $lats["kuwait"] = "29.3333000000";  $longs["kuwait"] = "47.9833000000"; $tzs["kuwait"] = "3.00"; $car["kuwait"] = "الكويت"; $cen["kuwait"] = "kuwait"; $countries["kuwait"] = "kuwait"; $area["kuwait"] = "ka"; $dstz["kuwait"] = "0"; $ram["kuwait"] = "0";
$id["liverpool"] = "159"; $city["liverpool"] = "liverpool"; $lats["liverpool"] = "53.4167000000";  $longs["liverpool"] = "-3.0000000000"; $tzs["liverpool"] = "0.00"; $car["liverpool"] = "ليفربول"; $cen["liverpool"] = "liverpool"; $countries["liverpool"] = "uk"; $area["liverpool"] = "bo"; $dstz["liverpool"] = "0"; $ram["liverpool"] = "0";
$id["london"] = "139"; $city["london"] = "london"; $lats["london"] = "51.5000000000";  $longs["london"] = "-0.1167000000"; $tzs["london"] = "0.00"; $car["london"] = "لندن"; $cen["london"] = "london"; $countries["london"] = "uk"; $area["london"] = "bo"; $dstz["london"] = "0"; $ram["london"] = "0";
$id["losangeles"] = "117"; $city["losangeles"] = "losangeles"; $lats["losangeles"] = "33.9733000000";  $longs["losangeles"] = "-118.2487000000"; $tzs["losangeles"] = "-8.00"; $car["losangeles"] = "لوس انجلوس"; $cen["losangeles"] = "Los Angeles"; $countries["losangeles"] = "usa"; $area["losangeles"] = "us"; $dstz["losangeles"] = "1"; $ram["losangeles"] = "0";
$id["luxur"] = "162"; $city["luxur"] = "luxur"; $lats["luxur"] = "25.6833000000";  $longs["luxur"] = "32.6500000000"; $tzs["luxur"] = "2.00"; $car["luxur"] = "الاقصر"; $cen["luxur"] = "luxur"; $countries["luxur"] = "egypt"; $area["luxur"] = "eg"; $dstz["luxur"] = "0"; $ram["luxur"] = "0";
$id["lyon"] = "163"; $city["lyon"] = "lyon"; $lats["lyon"] = "45.7500000000";  $longs["lyon"] = "4.8500000000"; $tzs["lyon"] = "1.00"; $car["lyon"] = "ليون"; $cen["lyon"] = "lyon"; $countries["lyon"] = "france"; $area["lyon"] = "bo"; $dstz["lyon"] = "0"; $ram["lyon"] = "0";
$id["madaba"] = "104"; $city["madaba"] = "madaba"; $lats["madaba"] = "31.7167000000";  $longs["madaba"] = "35.8000000000"; $tzs["madaba"] = "2.00"; $car["madaba"] = "مادبا"; $cen["madaba"] = "madaba"; $countries["madaba"] = "jordan"; $area["madaba"] = "um"; $dstz["madaba"] = "0"; $ram["madaba"] = "0";
$id["madinah"] = "32"; $city["madinah"] = "madinah"; $lats["madinah"] = "24.4667000000";  $longs["madinah"] = "39.6000000000"; $tzs["madinah"] = "3.00"; $car["madinah"] = "المدينة المنورة"; $cen["madinah"] = "madinah"; $countries["madinah"] = "ksa"; $area["madinah"] = "um"; $dstz["madinah"] = "0"; $ram["madinah"] = "0";
$id["majmaah"] = "31"; $city["majmaah"] = "majmaah"; $lats["majmaah"] = "25.9038890000";  $longs["majmaah"] = "45.3455560000"; $tzs["majmaah"] = "3.00"; $car["majmaah"] = "المجمعة"; $cen["majmaah"] = "majmaah"; $countries["majmaah"] = "ksa"; $area["majmaah"] = "um"; $dstz["majmaah"] = "0"; $ram["majmaah"] = "0";
$id["manchester"] = "154"; $city["manchester"] = "manchester"; $lats["manchester"] = "53.5000000000";  $longs["manchester"] = "-2.2167000000"; $tzs["manchester"] = "0.00"; $car["manchester"] = "مانشستر"; $cen["manchester"] = "manchester"; $countries["manchester"] = "uk"; $area["manchester"] = "bo"; $dstz["manchester"] = "0"; $ram["manchester"] = "0";
$id["marrakech"] = "79"; $city["marrakech"] = "marrakech"; $lats["marrakech"] = "31.6167000000";  $longs["marrakech"] = "-8.0333300000"; $tzs["marrakech"] = "0.00"; $car["marrakech"] = "مراكش"; $cen["marrakech"] = "marrakech"; $countries["marrakech"] = "morocco"; $area["marrakech"] = "bo"; $dstz["marrakech"] = "0"; $ram["marrakech"] = "0";
$id["mascara"] = "66"; $city["mascara"] = "mascara"; $lats["mascara"] = "35.4000000000";  $longs["mascara"] = "0.1330000000"; $tzs["mascara"] = "1.00"; $car["mascara"] = "معسكر"; $cen["mascara"] = "mascara"; $countries["mascara"] = "algeria"; $area["mascara"] = "bo"; $dstz["mascara"] = "0"; $ram["mascara"] = "0";
$id["matrouh"] = "54"; $city["matrouh"] = "matrouh"; $lats["matrouh"] = "31.3500000000";  $longs["matrouh"] = "27.2333000000"; $tzs["matrouh"] = "2.00"; $car["matrouh"] = "مرسى مطروح"; $cen["matrouh"] = "Marsa Matrouh"; $countries["matrouh"] = "egypt"; $area["matrouh"] = "eg"; $dstz["matrouh"] = "0"; $ram["matrouh"] = "0";
$id["mecca"] = "33"; $city["mecca"] = "mecca"; $lats["mecca"] = "21.4266670000";  $longs["mecca"] = "39.8261110000"; $tzs["mecca"] = "3.00"; $car["mecca"] = "مكة المكرمة"; $cen["mecca"] = "mecca"; $countries["mecca"] = "ksa"; $area["mecca"] = "um"; $dstz["mecca"] = "0"; $ram["mecca"] = "0";
$id["meknes"] = "80"; $city["meknes"] = "meknes"; $lats["meknes"] = "33.8833000000";  $longs["meknes"] = "-5.5333300000"; $tzs["meknes"] = "0.00"; $car["meknes"] = "مكناس"; $cen["meknes"] = "meknes"; $countries["meknes"] = "morocco"; $area["meknes"] = "bo"; $dstz["meknes"] = "0"; $ram["meknes"] = "0";
$id["menofia"] = "55"; $city["menofia"] = "menofia"; $lats["menofia"] = "30.5000000000";  $longs["menofia"] = "31.0000000000"; $tzs["menofia"] = "2.00"; $car["menofia"] = "المنوفية"; $cen["menofia"] = "menofia"; $countries["menofia"] = "egypt"; $area["menofia"] = "eg"; $dstz["menofia"] = "0"; $ram["menofia"] = "0";
$id["minia"] = "56"; $city["minia"] = "minia"; $lats["minia"] = "28.1000000000";  $longs["minia"] = "30.7500000000"; $tzs["minia"] = "2.00"; $car["minia"] = "المنيا"; $cen["minia"] = "minia"; $countries["minia"] = "egypt"; $area["minia"] = "eg"; $dstz["minia"] = "0"; $ram["minia"] = "0";
$id["minneapolis"] = "121"; $city["minneapolis"] = "minneapolis"; $lats["minneapolis"] = "44.9847000000";  $longs["minneapolis"] = "-93.2709000000"; $tzs["minneapolis"] = "-6.00"; $car["minneapolis"] = "مينيابوليس"; $cen["minneapolis"] = "Minneapolis"; $countries["minneapolis"] = "usa"; $area["minneapolis"] = "us"; $dstz["minneapolis"] = "1"; $ram["minneapolis"] = "0";
$id["misurata"] = "101"; $city["misurata"] = "misurata"; $lats["misurata"] = "32.3783000000";  $longs["misurata"] = "15.0906000000"; $tzs["misurata"] = "2.00"; $car["misurata"] = "مصراتة"; $cen["misurata"] = "misurata"; $countries["misurata"] = "libya"; $area["misurata"] = "eg"; $dstz["misurata"] = "0"; $ram["misurata"] = "0";
$id["mosul"] = "91"; $city["mosul"] = "mosul"; $lats["mosul"] = "36.3167000000";  $longs["mosul"] = "43.1500000000"; $tzs["mosul"] = "3.00"; $car["mosul"] = "الموصل"; $cen["mosul"] = "mosul"; $countries["mosul"] = "iraq"; $area["mosul"] = "bo"; $dstz["mosul"] = "0"; $ram["mosul"] = "0";
$id["mukalla"] = "111"; $city["mukalla"] = "mukalla"; $lats["mukalla"] = "14.5300000000";  $longs["mukalla"] = "49.1314000000"; $tzs["mukalla"] = "3.00"; $car["mukalla"] = "المكلا"; $cen["mukalla"] = "mukalla"; $countries["mukalla"] = "yemen"; $area["mukalla"] = "um"; $dstz["mukalla"] = "0"; $ram["mukalla"] = "0";
$id["muscat"] = "106"; $city["muscat"] = "muscat"; $lats["muscat"] = "23.6133000000";  $longs["muscat"] = "58.5933000000"; $tzs["muscat"] = "4.00"; $car["muscat"] = "مسقط"; $cen["muscat"] = "muscat"; $countries["muscat"] = "oman"; $area["muscat"] = "um"; $dstz["muscat"] = "0"; $ram["muscat"] = "0";
$id["najaf"] = "92"; $city["najaf"] = "najaf"; $lats["najaf"] = "31.9833000000";  $longs["najaf"] = "44.3333000000"; $tzs["najaf"] = "3.00"; $car["najaf"] = "النجف"; $cen["najaf"] = "najaf"; $countries["najaf"] = "iraq"; $area["najaf"] = "bo"; $dstz["najaf"] = "0"; $ram["najaf"] = "0";
$id["najran"] = "34"; $city["najran"] = "najran"; $lats["najran"] = "17.5000000000";  $longs["najran"] = "44.1667000000"; $tzs["najran"] = "3.00"; $car["najran"] = "نجران"; $cen["najran"] = "najran"; $countries["najran"] = "ksa"; $area["najran"] = "um"; $dstz["najran"] = "0"; $ram["najran"] = "0";
$id["newyork"] = "114"; $city["newyork"] = "newyork"; $lats["newyork"] = "40.7500000000";  $longs["newyork"] = "-73.9967000000"; $tzs["newyork"] = "-5.00"; $car["newyork"] = "نيويورك"; $cen["newyork"] = "New York"; $countries["newyork"] = "usa"; $area["newyork"] = "us"; $dstz["newyork"] = "1"; $ram["newyork"] = "0";
$id["paris"] = "145"; $city["paris"] = "paris"; $lats["paris"] = "48.8667000000";  $longs["paris"] = "2.3333000000"; $tzs["paris"] = "1.00"; $car["paris"] = "باريس"; $cen["paris"] = "paris"; $countries["paris"] = "france"; $area["paris"] = "bo"; $dstz["paris"] = "0"; $ram["paris"] = "0";
$id["portsaid"] = "42"; $city["portsaid"] = "portsaid"; $lats["portsaid"] = "31.2667000000";  $longs["portsaid"] = "32.3000000000"; $tzs["portsaid"] = "2.00"; $car["portsaid"] = "بورسعيد"; $cen["portsaid"] = "Port Said"; $countries["portsaid"] = "egypt"; $area["portsaid"] = "eg"; $dstz["portsaid"] = "0"; $ram["portsaid"] = "0";
$id["portsudan"] = "83"; $city["portsudan"] = "portsudan"; $lats["portsudan"] = "19.4333000000";  $longs["portsudan"] = "37.2333000000"; $tzs["portsudan"] = "3.00"; $car["portsudan"] = "بور سودان"; $cen["portsudan"] = "portsudan"; $countries["portsudan"] = "sudan"; $area["portsudan"] = "bo"; $dstz["portsudan"] = "0"; $ram["portsudan"] = "0";
$id["qassim"] = "29"; $city["qassim"] = "qassim"; $lats["qassim"] = "27.0833000000";  $longs["qassim"] = "43.4667000000"; $tzs["qassim"] = "3.00"; $car["qassim"] = "القصيم"; $cen["qassim"] = "qassim"; $countries["qassim"] = "ksa"; $area["qassim"] = "um"; $dstz["qassim"] = "0"; $ram["qassim"] = "0";
$id["qatif"] = "30"; $city["qatif"] = "qatif"; $lats["qatif"] = "26.9333330000";  $longs["qatif"] = "50.0166670000"; $tzs["qatif"] = "3.00"; $car["qatif"] = "القطيف"; $cen["qatif"] = "qatif"; $countries["qatif"] = "ksa"; $area["qatif"] = "um"; $dstz["qatif"] = "0"; $ram["qatif"] = "0";
$id["qina"] = "153"; $city["qina"] = "qina"; $lats["qina"] = "26.1700000000";  $longs["qina"] = "32.7272000000"; $tzs["qina"] = "2.00"; $car["qina"] = "قنا"; $cen["qina"] = "qina"; $countries["qina"] = "egypt"; $area["qina"] = "eg"; $dstz["qina"] = "0"; $ram["qina"] = "0";
$id["quarayat"] = "142"; $city["quarayat"] = "quarayat"; $lats["quarayat"] = "18.3416000000";  $longs["quarayat"] = "42.4647000000"; $tzs["quarayat"] = "3.00"; $car["quarayat"] = "القريات"; $cen["quarayat"] = "quarayat"; $countries["quarayat"] = "ksa"; $area["quarayat"] = "um"; $dstz["quarayat"] = "0"; $ram["quarayat"] = "0";
$id["rabat"] = "72"; $city["rabat"] = "rabat"; $lats["rabat"] = "34.0333000000";  $longs["rabat"] = "-6.8500000000"; $tzs["rabat"] = "0.00"; $car["rabat"] = "الرباط"; $cen["rabat"] = "rabat"; $countries["rabat"] = "morocco"; $area["rabat"] = "bo"; $dstz["rabat"] = "0"; $ram["rabat"] = "0";
$id["rasalkhaima"] = "59"; $city["rasalkhaima"] = "rasalkhaima"; $lats["rasalkhaima"] = "25.7833000000";  $longs["rasalkhaima"] = "55.9333000000"; $tzs["rasalkhaima"] = "4.00"; $car["rasalkhaima"] = "راس الخيمة"; $cen["rasalkhaima"] = "Ras Al Khaimah"; $countries["rasalkhaima"] = "uae"; $area["rasalkhaima"] = "um"; $dstz["rasalkhaima"] = "0"; $ram["rasalkhaima"] = "0";
$id["riyadh"] = "21"; $city["riyadh"] = "riyadh"; $lats["riyadh"] = "24.6333000000";  $longs["riyadh"] = "46.7167000000"; $tzs["riyadh"] = "3.00"; $car["riyadh"] = "الرياض"; $cen["riyadh"] = "riyadh"; $countries["riyadh"] = "ksa"; $area["riyadh"] = "um"; $dstz["riyadh"] = "0"; $ram["riyadh"] = "0";
$id["rome"] = "152"; $city["rome"] = "rome"; $lats["rome"] = "41.9000000000";  $longs["rome"] = "12.4833000000"; $tzs["rome"] = "1.00"; $car["rome"] = "روما"; $cen["rome"] = "rome"; $countries["rome"] = "italy"; $area["rome"] = "bo"; $dstz["rome"] = "1"; $ram["rome"] = "0";
$id["salala"] = "105"; $city["salala"] = "salala"; $lats["salala"] = "17.0175000000";  $longs["salala"] = "54.0828000000"; $tzs["salala"] = "4.00"; $car["salala"] = "صلالة"; $cen["salala"] = "salala"; $countries["salala"] = "oman"; $area["salala"] = "um"; $dstz["salala"] = "0"; $ram["salala"] = "0";
$id["sanaa"] = "112"; $city["sanaa"] = "sanaa"; $lats["sanaa"] = "15.3547000000";  $longs["sanaa"] = "44.2067000000"; $tzs["sanaa"] = "3.00"; $car["sanaa"] = "صنعاء"; $cen["sanaa"] = "sanaa"; $countries["sanaa"] = "yemen"; $area["sanaa"] = "um"; $dstz["sanaa"] = "0"; $ram["sanaa"] = "0";
$id["sanfrancisco"] = "120"; $city["sanfrancisco"] = "sanfrancisco"; $lats["sanfrancisco"] = "37.7753000000";  $longs["sanfrancisco"] = "-122.4186000000"; $tzs["sanfrancisco"] = "-8.00"; $car["sanfrancisco"] = "سان فرانسيسكو"; $cen["sanfrancisco"] = "San Francisco"; $countries["sanfrancisco"] = "usa"; $area["sanfrancisco"] = "us"; $dstz["sanfrancisco"] = "1"; $ram["sanfrancisco"] = "0";
$id["seattle"] = "116"; $city["seattle"] = "seattle"; $lats["seattle"] = "47.6115000000";  $longs["seattle"] = "-122.3343000000"; $tzs["seattle"] = "-8.00"; $car["seattle"] = "سياتل"; $cen["seattle"] = "Seattle"; $countries["seattle"] = "usa"; $area["seattle"] = "us"; $dstz["seattle"] = "1"; $ram["seattle"] = "0";
$id["sebha"] = "98"; $city["sebha"] = "sebha"; $lats["sebha"] = "27.0333000000";  $longs["sebha"] = "14.4333000000"; $tzs["sebha"] = "2.00"; $car["sebha"] = "سبها"; $cen["sebha"] = "sebha"; $countries["sebha"] = "libya"; $area["sebha"] = "eg"; $dstz["sebha"] = "0"; $ram["sebha"] = "0";
$id["shaqra"] = "138"; $city["shaqra"] = "shaqra"; $lats["shaqra"] = "25.2506000000";  $longs["shaqra"] = "45.2542000000"; $tzs["shaqra"] = "3.00"; $car["shaqra"] = "شقرا"; $cen["shaqra"] = "shaqra"; $countries["shaqra"] = "ksa"; $area["shaqra"] = "um"; $dstz["shaqra"] = "0"; $ram["shaqra"] = "0";
$id["sharjah"] = "60"; $city["sharjah"] = "sharjah"; $lats["sharjah"] = "25.3333000000";  $longs["sharjah"] = "55.4333000000"; $tzs["sharjah"] = "4.00"; $car["sharjah"] = "الشارقة"; $cen["sharjah"] = "sharjah"; $countries["sharjah"] = "uae"; $area["sharjah"] = "um"; $dstz["sharjah"] = "0"; $ram["sharjah"] = "0";
$id["sharm"] = "48"; $city["sharm"] = "sharm"; $lats["sharm"] = "27.8500000000";  $longs["sharm"] = "34.2667000000"; $tzs["sharm"] = "2.00"; $car["sharm"] = "شرم الشيخ"; $cen["sharm"] = "Sharm El Sheikh"; $countries["sharm"] = "egypt"; $area["sharm"] = "eg"; $dstz["sharm"] = "0"; $ram["sharm"] = "0";
$id["sheffield"] = "144"; $city["sheffield"] = "sheffield"; $lats["sheffield"] = "53.3667000000";  $longs["sheffield"] = "-1.5000000000"; $tzs["sheffield"] = "0.00"; $car["sheffield"] = "شيفيلد"; $cen["sheffield"] = "sheffield"; $countries["sheffield"] = "uk"; $area["sheffield"] = "bo"; $dstz["sheffield"] = "0"; $ram["sheffield"] = "0";
$id["sohag"] = "46"; $city["sohag"] = "sohag"; $lats["sohag"] = "26.5500000000";  $longs["sohag"] = "31.7000000000"; $tzs["sohag"] = "2.00"; $car["sohag"] = "سوهاج"; $cen["sohag"] = "sohag"; $countries["sohag"] = "egypt"; $area["sohag"] = "eg"; $dstz["sohag"] = "0"; $ram["sohag"] = "0";
$id["suez"] = "47"; $city["suez"] = "suez"; $lats["suez"] = "29.9667000000";  $longs["suez"] = "32.5500000000"; $tzs["suez"] = "2.00"; $car["suez"] = "السويس"; $cen["suez"] = "suez"; $countries["suez"] = "egypt"; $area["suez"] = "eg"; $dstz["suez"] = "0"; $ram["suez"] = "0";
$id["sulayyil"] = "160"; $city["sulayyil"] = "sulayyil"; $lats["sulayyil"] = "20.6667000000";  $longs["sulayyil"] = "45.6667000000"; $tzs["sulayyil"] = "3.00"; $car["sulayyil"] = "السليل"; $cen["sulayyil"] = "sulayyil"; $countries["sulayyil"] = "ksa"; $area["sulayyil"] = "um"; $dstz["sulayyil"] = "0"; $ram["sulayyil"] = "0";
$id["tabouk"] = "6"; $city["tabouk"] = "tabouk"; $lats["tabouk"] = "28.3667000000";  $longs["tabouk"] = "36.6000000000"; $tzs["tabouk"] = "3.00"; $car["tabouk"] = "تبوك"; $cen["tabouk"] = "tabouk"; $countries["tabouk"] = "ksa"; $area["tabouk"] = "um"; $dstz["tabouk"] = "0"; $ram["tabouk"] = "0";
$id["taif"] = "24"; $city["taif"] = "taif"; $lats["taif"] = "21.2500000000";  $longs["taif"] = "40.4167000000"; $tzs["taif"] = "3.00"; $car["taif"] = "الطائف"; $cen["taif"] = "taif"; $countries["taif"] = "ksa"; $area["taif"] = "um"; $dstz["taif"] = "0"; $ram["taif"] = "0";
$id["taiz"] = "113"; $city["taiz"] = "taiz"; $lats["taiz"] = "13.5000000000";  $longs["taiz"] = "44.0000000000"; $tzs["taiz"] = "3.00"; $car["taiz"] = "تعز"; $cen["taiz"] = "taiz"; $countries["taiz"] = "yemen"; $area["taiz"] = "um"; $dstz["taiz"] = "0"; $ram["taiz"] = "0";
$id["tangier"] = "75"; $city["tangier"] = "tangier"; $lats["tangier"] = "35.8000000000";  $longs["tangier"] = "-5.7500000000"; $tzs["tangier"] = "0.00"; $car["tangier"] = "طنجة"; $cen["tangier"] = "tangier"; $countries["tangier"] = "morocco"; $area["tangier"] = "bo"; $dstz["tangier"] = "0"; $ram["tangier"] = "0";
$id["tanta"] = "49"; $city["tanta"] = "tanta"; $lats["tanta"] = "30.7833000000";  $longs["tanta"] = "31.0000000000"; $tzs["tanta"] = "2.00"; $car["tanta"] = "طنطا"; $cen["tanta"] = "tanta"; $countries["tanta"] = "egypt"; $area["tanta"] = "eg"; $dstz["tanta"] = "0"; $ram["tanta"] = "0";
$id["tanura"] = "20"; $city["tanura"] = "tanura"; $lats["tanura"] = "26.6500000000";  $longs["tanura"] = "50.1666670000"; $tzs["tanura"] = "3.00"; $car["tanura"] = "راس تنورة"; $cen["tanura"] = "Ras Tanura"; $countries["tanura"] = "ksa"; $area["tanura"] = "um"; $dstz["tanura"] = "0"; $ram["tanura"] = "0";
$id["tartous"] = "161"; $city["tartous"] = "tartous"; $lats["tartous"] = "34.8333000000";  $longs["tartous"] = "35.9167000000"; $tzs["tartous"] = "2.00"; $car["tartous"] = "طرطوس"; $cen["tartous"] = "tartous"; $countries["tartous"] = "syria"; $area["tartous"] = "um"; $dstz["tartous"] = "0"; $ram["tartous"] = "0";
$id["telmcen"] = "62"; $city["telmcen"] = "telmcen"; $lats["telmcen"] = "34.8667000000";  $longs["telmcen"] = "-1.2500000000"; $tzs["telmcen"] = "1.00"; $car["telmcen"] = "تلمسان"; $cen["telmcen"] = "telmcen"; $countries["telmcen"] = "algeria"; $area["telmcen"] = "bo"; $dstz["telmcen"] = "0"; $ram["telmcen"] = "0";
$id["tetouan"] = "74"; $city["tetouan"] = "tetouan"; $lats["tetouan"] = "35.5667000000";  $longs["tetouan"] = "-5.3833300000"; $tzs["tetouan"] = "0.00"; $car["tetouan"] = "تطوان"; $cen["tetouan"] = "tetouan"; $countries["tetouan"] = "morocco"; $area["tetouan"] = "bo"; $dstz["tetouan"] = "0"; $ram["tetouan"] = "0";
$id["toulouse"] = "155"; $city["toulouse"] = "toulouse"; $lats["toulouse"] = "43.6000000000";  $longs["toulouse"] = "1.4333000000"; $tzs["toulouse"] = "1.00"; $car["toulouse"] = "تولوز"; $cen["toulouse"] = "toulouse"; $countries["toulouse"] = "france"; $area["toulouse"] = "bo"; $dstz["toulouse"] = "0"; $ram["toulouse"] = "0";
$id["tripoli"] = "100"; $city["tripoli"] = "tripoli"; $lats["tripoli"] = "32.8925000000";  $longs["tripoli"] = "13.1800000000"; $tzs["tripoli"] = "2.00"; $car["tripoli"] = "طرابلس"; $cen["tripoli"] = "tripoli"; $countries["tripoli"] = "libya"; $area["tripoli"] = "eg"; $dstz["tripoli"] = "0"; $ram["tripoli"] = "0";
$id["tubruq"] = "99"; $city["tubruq"] = "tubruq"; $lats["tubruq"] = "32.0836000000";  $longs["tubruq"] = "23.9764000000"; $tzs["tubruq"] = "2.00"; $car["tubruq"] = "طبرق"; $cen["tubruq"] = "tubruq"; $countries["tubruq"] = "libya"; $area["tubruq"] = "eg"; $dstz["tubruq"] = "0"; $ram["tubruq"] = "0";
$id["tunis"] = "141"; $city["tunis"] = "tunis"; $lats["tunis"] = "36.8028000000";  $longs["tunis"] = "10.1797000000"; $tzs["tunis"] = "1.00"; $car["tunis"] = "تونس"; $cen["tunis"] = "tunis"; $countries["tunis"] = "tunisia"; $area["tunis"] = "bo"; $dstz["tunis"] = "0"; $ram["tunis"] = "0";
$id["ubayyid"] = "81"; $city["ubayyid"] = "ubayyid"; $lats["ubayyid"] = "13.1667000000";  $longs["ubayyid"] = "30.2333000000"; $tzs["ubayyid"] = "3.00"; $car["ubayyid"] = "الابيض"; $cen["ubayyid"] = "ubayyid"; $countries["ubayyid"] = "sudan"; $area["ubayyid"] = "bo"; $dstz["ubayyid"] = "0"; $ram["ubayyid"] = "0";
$id["ula"] = "140"; $city["ula"] = "ula"; $lats["ula"] = "26.6333000000";  $longs["ula"] = "37.9167000000"; $tzs["ula"] = "3.00"; $car["ula"] = "العلا"; $cen["ula"] = "ula"; $countries["ula"] = "ksa"; $area["ula"] = "um"; $dstz["ula"] = "0"; $ram["ula"] = "0";
$id["unaizah"] = "28"; $city["unaizah"] = "unaizah"; $lats["unaizah"] = "26.0840000000";  $longs["unaizah"] = "43.9940000000"; $tzs["unaizah"] = "3.00"; $car["unaizah"] = "عنيزة"; $cen["unaizah"] = "unaizah"; $countries["unaizah"] = "ksa"; $area["unaizah"] = "um"; $dstz["unaizah"] = "0"; $ram["unaizah"] = "0";
$id["venice"] = "137"; $city["venice"] = "venice"; $lats["venice"] = "45.5833000000";  $longs["venice"] = "12.5667000000"; $tzs["venice"] = "1.00"; $car["venice"] = "فينيسيا"; $cen["venice"] = "venice"; $countries["venice"] = "italy"; $area["venice"] = "bo"; $dstz["venice"] = "1"; $ram["venice"] = "0";
$id["wadihalfa"] = "85"; $city["wadihalfa"] = "wadihalfa"; $lats["wadihalfa"] = "21.8167000000";  $longs["wadihalfa"] = "31.3667000000"; $tzs["wadihalfa"] = "3.00"; $car["wadihalfa"] = "وادي حلفا"; $cen["wadihalfa"] = "wadihalfa"; $countries["wadihalfa"] = "sudan"; $area["wadihalfa"] = "bo"; $dstz["wadihalfa"] = "0"; $ram["wadihalfa"] = "0";
$id["washington"] = "115"; $city["washington"] = "washington"; $lats["washington"] = "38.9102000000";  $longs["washington"] = "-77.0179000000"; $tzs["washington"] = "-5.00"; $car["washington"] = "واشنطن"; $cen["washington"] = "Washington"; $countries["washington"] = "usa"; $area["washington"] = "us"; $dstz["washington"] = "1"; $ram["washington"] = "0";
$id["yanbu"] = "36"; $city["yanbu"] = "yanbu"; $lats["yanbu"] = "24.1500000000";  $longs["yanbu"] = "38.0667000000"; $tzs["yanbu"] = "3.00"; $car["yanbu"] = "ينبع"; $cen["yanbu"] = "yanbu"; $countries["yanbu"] = "ksa"; $area["yanbu"] = "um"; $dstz["yanbu"] = "0"; $ram["yanbu"] = "0";
$id["zagazig"] = "45"; $city["zagazig"] = "zagazig"; $lats["zagazig"] = "30.5667000000";  $longs["zagazig"] = "31.5000000000"; $tzs["zagazig"] = "2.00"; $car["zagazig"] = "الزقازيق"; $cen["zagazig"] = "zagazig"; $countries["zagazig"] = "egypt"; $area["zagazig"] = "eg"; $dstz["zagazig"] = "0"; $ram["zagazig"] = "0";
$id["zulfi"] = "22"; $city["zulfi"] = "zulfi"; $lats["zulfi"] = "26.2833330000";  $longs["zulfi"] = "44.8000000000"; $tzs["zulfi"] = "3.00"; $car["zulfi"] = "الزلفي"; $cen["zulfi"] = "zulfi"; $countries["zulfi"] = "ksa"; $area["zulfi"] = "um"; $dstz["zulfi"] = "0"; $ram["zulfi"] = "0";
?>